data_process:
  test_size: 0.4
  random_state: 42
  correlation_threshold: 0.6  # Si tu changes ça, DVC relance le process

train:
  # Hyperparamètres pour LinearRegression (peu de paramètres disponibles)
  # Pour d'autres modèles, ajouter fit_intercept, normalize, etc.
  fit_intercept: true

eval:
  output_dir: metrics
